name: Daily IP Update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */3 * * *"  # Runs every three hours

permissions: write-all

jobs:
  update_ip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Get the Proxy IPs
        run: python "scripts/getIPs.py"

      - name: Test the Proxy IPs
        run: python "scripts/cfSpeedTest.py"

      - name: Map the IPs with domain names
        run: python "scripts/mapDomain.py"

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Commit and Push Changes
        run: |
          git add .
          git commit -m "Automated update of IP mappings and DNS records"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
